apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdm-ontologies-data
  namespace: cdm-ontologies
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti  # 2TB for large ontology files
  storageClassName: fast-ssd  # Adjust based on your cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdm-ontologies-cache
  namespace: cdm-ontologies
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi  # Cache for downloaded files
  storageClassName: standard