# Local Docker Compose override for ontology order testing
# This file overrides hardcoded memory settings from the main Dockerfile
# All contained within ontology_order_testing/ folder

version: '3.8'

services:
  cdm-ontologies:
    # Load environment from local env file
    env_file:
      - ./ontology_order_testing/local_env/.env.local
    # Override hardcoded Java memory settings from Dockerfile
    environment:
      # Override ROBOT_JAVA_ARGS from Dockerfile (1TB to match main pipeline)
      - ROBOT_JAVA_ARGS=-Xmx1024g -XX:MaxMetaspaceSize=8g -XX:+UseG1GC
      # Override _JAVA_OPTIONS from Dockerfile (1TB to match main pipeline) 
      - _JAVA_OPTIONS=-Xmx1024g -XX:MaxMetaspaceSize=8g -XX:+UseG1GC
      # Additional memory configurations (1TB to match main pipeline)
      - RELATION_GRAPH_JAVA_ARGS=-Xmx1024g -XX:MaxMetaspaceSize=8g -XX:+UseG1GC
      - SEMSQL_MEMORY_LIMIT=1024g
      - PYTHON_MEMORY_LIMIT=1024g
      - ENABLE_MEMORY_MONITORING=true
      - SKIP_RESOURCE_CHECK=true
      # Performance tuning
      - JAVA_PARALLEL_GC=true
      - ENABLE_TSV_EXPORT=false
      - ENABLE_PARQUET_EXPORT=false
      - CREATE_UTILS_LOGS=false